services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # On utilise l'étape 'builder' qui contient les outils Go et 'air'.
    container_name: go_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "${APP_PORT_HOST}:${APP_PORT_CONTAINER}"
    volumes:
      - .:/app
    command: air
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT_CONTAINER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - APP_PORT=${APP_PORT_CONTAINER}
    depends_on:
      db:
        condition: service_healthy
    networks:
      app_network:
        aliases:
          - go-app

  db:
    image: postgres:15-alpine@sha256:d5260755faa5e967902b74b4b9bf9c6ade5c40ed9620b76a675c6bc2ec8160df
    container_name: postgres_db_service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      app_network:
        aliases:
          - postgres

volumes:
  postgres_data: # Définit un volume nommé pour la persistance des données PostgreSQL

networks:
  app_network:
    driver: bridge
